// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: message.proto

package org.fancy.mq.core.serializer.protobuf;

public final class SimpleMessage {
  private SimpleMessage() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ProtoMessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:mq.ProtoMessage)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 code = 1;</code>
     * @return The code.
     */
    int getCode();

    /**
     * <code>string name = 2;</code>
     * @return The name.
     */
    java.lang.String getName();
    /**
     * <code>string name = 2;</code>
     * @return The bytes for name.
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <code>int64 timestamp = 3;</code>
     * @return The timestamp.
     */
    long getTimestamp();

    /**
     * <code>repeated .mq.ProtoMessage.PhoneNumber phones = 4;</code>
     */
    java.util.List<org.fancy.mq.core.serializer.protobuf.SimpleMessage.ProtoMessage.PhoneNumber> 
        getPhonesList();
    /**
     * <code>repeated .mq.ProtoMessage.PhoneNumber phones = 4;</code>
     */
    org.fancy.mq.core.serializer.protobuf.SimpleMessage.ProtoMessage.PhoneNumber getPhones(int index);
    /**
     * <code>repeated .mq.ProtoMessage.PhoneNumber phones = 4;</code>
     */
    int getPhonesCount();
    /**
     * <code>repeated .mq.ProtoMessage.PhoneNumber phones = 4;</code>
     */
    java.util.List<? extends org.fancy.mq.core.serializer.protobuf.SimpleMessage.ProtoMessage.PhoneNumberOrBuilder> 
        getPhonesOrBuilderList();
    /**
     * <code>repeated .mq.ProtoMessage.PhoneNumber phones = 4;</code>
     */
    org.fancy.mq.core.serializer.protobuf.SimpleMessage.ProtoMessage.PhoneNumberOrBuilder getPhonesOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code mq.ProtoMessage}
   */
  public static final class ProtoMessage extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:mq.ProtoMessage)
      ProtoMessageOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ProtoMessage.newBuilder() to construct.
    private ProtoMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ProtoMessage() {
      name_ = "";
      phones_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new ProtoMessage();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ProtoMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              code_ = input.readInt32();
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              name_ = s;
              break;
            }
            case 24: {

              timestamp_ = input.readInt64();
              break;
            }
            case 34: {
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                phones_ = new java.util.ArrayList<org.fancy.mq.core.serializer.protobuf.SimpleMessage.ProtoMessage.PhoneNumber>();
                mutable_bitField0_ |= 0x00000001;
              }
              phones_.add(
                  input.readMessage(org.fancy.mq.core.serializer.protobuf.SimpleMessage.ProtoMessage.PhoneNumber.parser(), extensionRegistry));
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) != 0)) {
          phones_ = java.util.Collections.unmodifiableList(phones_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.fancy.mq.core.serializer.protobuf.SimpleMessage.internal_static_mq_ProtoMessage_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.fancy.mq.core.serializer.protobuf.SimpleMessage.internal_static_mq_ProtoMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.fancy.mq.core.serializer.protobuf.SimpleMessage.ProtoMessage.class, org.fancy.mq.core.serializer.protobuf.SimpleMessage.ProtoMessage.Builder.class);
    }

    /**
     * Protobuf enum {@code mq.ProtoMessage.PhoneType}
     */
    public enum PhoneType
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>HOME = 0;</code>
       */
      HOME(0),
      /**
       * <code>MOBILE = 1;</code>
       */
      MOBILE(1),
      /**
       * <code>WORK = 2;</code>
       */
      WORK(2),
      UNRECOGNIZED(-1),
      ;

      /**
       * <code>HOME = 0;</code>
       */
      public static final int HOME_VALUE = 0;
      /**
       * <code>MOBILE = 1;</code>
       */
      public static final int MOBILE_VALUE = 1;
      /**
       * <code>WORK = 2;</code>
       */
      public static final int WORK_VALUE = 2;


      public final int getNumber() {
        if (this == UNRECOGNIZED) {
          throw new java.lang.IllegalArgumentException(
              "Can't get the number of an unknown enum value.");
        }
        return value;
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static PhoneType valueOf(int value) {
        return forNumber(value);
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       */
      public static PhoneType forNumber(int value) {
        switch (value) {
          case 0: return HOME;
          case 1: return MOBILE;
          case 2: return WORK;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<PhoneType>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          PhoneType> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<PhoneType>() {
              public PhoneType findValueByNumber(int number) {
                return PhoneType.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        if (this == UNRECOGNIZED) {
          throw new java.lang.IllegalStateException(
              "Can't get the descriptor of an unrecognized enum value.");
        }
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return org.fancy.mq.core.serializer.protobuf.SimpleMessage.ProtoMessage.getDescriptor().getEnumTypes().get(0);
      }

      private static final PhoneType[] VALUES = values();

      public static PhoneType valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        if (desc.getIndex() == -1) {
          return UNRECOGNIZED;
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private PhoneType(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:mq.ProtoMessage.PhoneType)
    }

    public interface PhoneNumberOrBuilder extends
        // @@protoc_insertion_point(interface_extends:mq.ProtoMessage.PhoneNumber)
        com.google.protobuf.MessageOrBuilder {

      /**
       * <code>string number = 1;</code>
       * @return The number.
       */
      java.lang.String getNumber();
      /**
       * <code>string number = 1;</code>
       * @return The bytes for number.
       */
      com.google.protobuf.ByteString
          getNumberBytes();

      /**
       * <code>.mq.ProtoMessage.PhoneType type = 2;</code>
       * @return The enum numeric value on the wire for type.
       */
      int getTypeValue();
      /**
       * <code>.mq.ProtoMessage.PhoneType type = 2;</code>
       * @return The type.
       */
      org.fancy.mq.core.serializer.protobuf.SimpleMessage.ProtoMessage.PhoneType getType();
    }
    /**
     * Protobuf type {@code mq.ProtoMessage.PhoneNumber}
     */
    public static final class PhoneNumber extends
        com.google.protobuf.GeneratedMessageV3 implements
        // @@protoc_insertion_point(message_implements:mq.ProtoMessage.PhoneNumber)
        PhoneNumberOrBuilder {
    private static final long serialVersionUID = 0L;
      // Use PhoneNumber.newBuilder() to construct.
      private PhoneNumber(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
        super(builder);
      }
      private PhoneNumber() {
        number_ = "";
        type_ = 0;
      }

      @java.lang.Override
      @SuppressWarnings({"unused"})
      protected java.lang.Object newInstance(
          UnusedPrivateParameter unused) {
        return new PhoneNumber();
      }

      @java.lang.Override
      public final com.google.protobuf.UnknownFieldSet
      getUnknownFields() {
        return this.unknownFields;
      }
      private PhoneNumber(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        this();
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                java.lang.String s = input.readStringRequireUtf8();

                number_ = s;
                break;
              }
              case 16: {
                int rawValue = input.readEnum();

                type_ = rawValue;
                break;
              }
              default: {
                if (!parseUnknownField(
                    input, unknownFields, extensionRegistry, tag)) {
                  done = true;
                }
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(
              e).setUnfinishedMessage(this);
        } finally {
          this.unknownFields = unknownFields.build();
          makeExtensionsImmutable();
        }
      }
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.fancy.mq.core.serializer.protobuf.SimpleMessage.internal_static_mq_ProtoMessage_PhoneNumber_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.fancy.mq.core.serializer.protobuf.SimpleMessage.internal_static_mq_ProtoMessage_PhoneNumber_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.fancy.mq.core.serializer.protobuf.SimpleMessage.ProtoMessage.PhoneNumber.class, org.fancy.mq.core.serializer.protobuf.SimpleMessage.ProtoMessage.PhoneNumber.Builder.class);
      }

      public static final int NUMBER_FIELD_NUMBER = 1;
      private volatile java.lang.Object number_;
      /**
       * <code>string number = 1;</code>
       * @return The number.
       */
      @java.lang.Override
      public java.lang.String getNumber() {
        java.lang.Object ref = number_;
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          number_ = s;
          return s;
        }
      }
      /**
       * <code>string number = 1;</code>
       * @return The bytes for number.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString
          getNumberBytes() {
        java.lang.Object ref = number_;
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          number_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      public static final int TYPE_FIELD_NUMBER = 2;
      private int type_;
      /**
       * <code>.mq.ProtoMessage.PhoneType type = 2;</code>
       * @return The enum numeric value on the wire for type.
       */
      @java.lang.Override public int getTypeValue() {
        return type_;
      }
      /**
       * <code>.mq.ProtoMessage.PhoneType type = 2;</code>
       * @return The type.
       */
      @java.lang.Override public org.fancy.mq.core.serializer.protobuf.SimpleMessage.ProtoMessage.PhoneType getType() {
        @SuppressWarnings("deprecation")
        org.fancy.mq.core.serializer.protobuf.SimpleMessage.ProtoMessage.PhoneType result = org.fancy.mq.core.serializer.protobuf.SimpleMessage.ProtoMessage.PhoneType.valueOf(type_);
        return result == null ? org.fancy.mq.core.serializer.protobuf.SimpleMessage.ProtoMessage.PhoneType.UNRECOGNIZED : result;
      }

      private byte memoizedIsInitialized = -1;
      @java.lang.Override
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        memoizedIsInitialized = 1;
        return true;
      }

      @java.lang.Override
      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        if (!getNumberBytes().isEmpty()) {
          com.google.protobuf.GeneratedMessageV3.writeString(output, 1, number_);
        }
        if (type_ != org.fancy.mq.core.serializer.protobuf.SimpleMessage.ProtoMessage.PhoneType.HOME.getNumber()) {
          output.writeEnum(2, type_);
        }
        unknownFields.writeTo(output);
      }

      @java.lang.Override
      public int getSerializedSize() {
        int size = memoizedSize;
        if (size != -1) return size;

        size = 0;
        if (!getNumberBytes().isEmpty()) {
          size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, number_);
        }
        if (type_ != org.fancy.mq.core.serializer.protobuf.SimpleMessage.ProtoMessage.PhoneType.HOME.getNumber()) {
          size += com.google.protobuf.CodedOutputStream
            .computeEnumSize(2, type_);
        }
        size += unknownFields.getSerializedSize();
        memoizedSize = size;
        return size;
      }

      @java.lang.Override
      public boolean equals(final java.lang.Object obj) {
        if (obj == this) {
         return true;
        }
        if (!(obj instanceof org.fancy.mq.core.serializer.protobuf.SimpleMessage.ProtoMessage.PhoneNumber)) {
          return super.equals(obj);
        }
        org.fancy.mq.core.serializer.protobuf.SimpleMessage.ProtoMessage.PhoneNumber other = (org.fancy.mq.core.serializer.protobuf.SimpleMessage.ProtoMessage.PhoneNumber) obj;

        if (!getNumber()
            .equals(other.getNumber())) return false;
        if (type_ != other.type_) return false;
        if (!unknownFields.equals(other.unknownFields)) return false;
        return true;
      }

      @java.lang.Override
      public int hashCode() {
        if (memoizedHashCode != 0) {
          return memoizedHashCode;
        }
        int hash = 41;
        hash = (19 * hash) + getDescriptor().hashCode();
        hash = (37 * hash) + NUMBER_FIELD_NUMBER;
        hash = (53 * hash) + getNumber().hashCode();
        hash = (37 * hash) + TYPE_FIELD_NUMBER;
        hash = (53 * hash) + type_;
        hash = (29 * hash) + unknownFields.hashCode();
        memoizedHashCode = hash;
        return hash;
      }

      public static org.fancy.mq.core.serializer.protobuf.SimpleMessage.ProtoMessage.PhoneNumber parseFrom(
          java.nio.ByteBuffer data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static org.fancy.mq.core.serializer.protobuf.SimpleMessage.ProtoMessage.PhoneNumber parseFrom(
          java.nio.ByteBuffer data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static org.fancy.mq.core.serializer.protobuf.SimpleMessage.ProtoMessage.PhoneNumber parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static org.fancy.mq.core.serializer.protobuf.SimpleMessage.ProtoMessage.PhoneNumber parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static org.fancy.mq.core.serializer.protobuf.SimpleMessage.ProtoMessage.PhoneNumber parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static org.fancy.mq.core.serializer.protobuf.SimpleMessage.ProtoMessage.PhoneNumber parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static org.fancy.mq.core.serializer.protobuf.SimpleMessage.ProtoMessage.PhoneNumber parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static org.fancy.mq.core.serializer.protobuf.SimpleMessage.ProtoMessage.PhoneNumber parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }
      public static org.fancy.mq.core.serializer.protobuf.SimpleMessage.ProtoMessage.PhoneNumber parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input);
      }
      public static org.fancy.mq.core.serializer.protobuf.SimpleMessage.ProtoMessage.PhoneNumber parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
      }
      public static org.fancy.mq.core.serializer.protobuf.SimpleMessage.ProtoMessage.PhoneNumber parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static org.fancy.mq.core.serializer.protobuf.SimpleMessage.ProtoMessage.PhoneNumber parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }

      @java.lang.Override
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder() {
        return DEFAULT_INSTANCE.toBuilder();
      }
      public static Builder newBuilder(org.fancy.mq.core.serializer.protobuf.SimpleMessage.ProtoMessage.PhoneNumber prototype) {
        return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
      }
      @java.lang.Override
      public Builder toBuilder() {
        return this == DEFAULT_INSTANCE
            ? new Builder() : new Builder().mergeFrom(this);
      }

      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code mq.ProtoMessage.PhoneNumber}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
          // @@protoc_insertion_point(builder_implements:mq.ProtoMessage.PhoneNumber)
          org.fancy.mq.core.serializer.protobuf.SimpleMessage.ProtoMessage.PhoneNumberOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return org.fancy.mq.core.serializer.protobuf.SimpleMessage.internal_static_mq_ProtoMessage_PhoneNumber_descriptor;
        }

        @java.lang.Override
        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return org.fancy.mq.core.serializer.protobuf.SimpleMessage.internal_static_mq_ProtoMessage_PhoneNumber_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  org.fancy.mq.core.serializer.protobuf.SimpleMessage.ProtoMessage.PhoneNumber.class, org.fancy.mq.core.serializer.protobuf.SimpleMessage.ProtoMessage.PhoneNumber.Builder.class);
        }

        // Construct using org.fancy.mq.core.serializer.protobuf.SimpleMessage.ProtoMessage.PhoneNumber.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }

        private Builder(
            com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessageV3
                  .alwaysUseFieldBuilders) {
          }
        }
        @java.lang.Override
        public Builder clear() {
          super.clear();
          number_ = "";

          type_ = 0;

          return this;
        }

        @java.lang.Override
        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return org.fancy.mq.core.serializer.protobuf.SimpleMessage.internal_static_mq_ProtoMessage_PhoneNumber_descriptor;
        }

        @java.lang.Override
        public org.fancy.mq.core.serializer.protobuf.SimpleMessage.ProtoMessage.PhoneNumber getDefaultInstanceForType() {
          return org.fancy.mq.core.serializer.protobuf.SimpleMessage.ProtoMessage.PhoneNumber.getDefaultInstance();
        }

        @java.lang.Override
        public org.fancy.mq.core.serializer.protobuf.SimpleMessage.ProtoMessage.PhoneNumber build() {
          org.fancy.mq.core.serializer.protobuf.SimpleMessage.ProtoMessage.PhoneNumber result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        @java.lang.Override
        public org.fancy.mq.core.serializer.protobuf.SimpleMessage.ProtoMessage.PhoneNumber buildPartial() {
          org.fancy.mq.core.serializer.protobuf.SimpleMessage.ProtoMessage.PhoneNumber result = new org.fancy.mq.core.serializer.protobuf.SimpleMessage.ProtoMessage.PhoneNumber(this);
          result.number_ = number_;
          result.type_ = type_;
          onBuilt();
          return result;
        }

        @java.lang.Override
        public Builder clone() {
          return super.clone();
        }
        @java.lang.Override
        public Builder setField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            java.lang.Object value) {
          return super.setField(field, value);
        }
        @java.lang.Override
        public Builder clearField(
            com.google.protobuf.Descriptors.FieldDescriptor field) {
          return super.clearField(field);
        }
        @java.lang.Override
        public Builder clearOneof(
            com.google.protobuf.Descriptors.OneofDescriptor oneof) {
          return super.clearOneof(oneof);
        }
        @java.lang.Override
        public Builder setRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            int index, java.lang.Object value) {
          return super.setRepeatedField(field, index, value);
        }
        @java.lang.Override
        public Builder addRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            java.lang.Object value) {
          return super.addRepeatedField(field, value);
        }
        @java.lang.Override
        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof org.fancy.mq.core.serializer.protobuf.SimpleMessage.ProtoMessage.PhoneNumber) {
            return mergeFrom((org.fancy.mq.core.serializer.protobuf.SimpleMessage.ProtoMessage.PhoneNumber)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(org.fancy.mq.core.serializer.protobuf.SimpleMessage.ProtoMessage.PhoneNumber other) {
          if (other == org.fancy.mq.core.serializer.protobuf.SimpleMessage.ProtoMessage.PhoneNumber.getDefaultInstance()) return this;
          if (!other.getNumber().isEmpty()) {
            number_ = other.number_;
            onChanged();
          }
          if (other.type_ != 0) {
            setTypeValue(other.getTypeValue());
          }
          this.mergeUnknownFields(other.unknownFields);
          onChanged();
          return this;
        }

        @java.lang.Override
        public final boolean isInitialized() {
          return true;
        }

        @java.lang.Override
        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          org.fancy.mq.core.serializer.protobuf.SimpleMessage.ProtoMessage.PhoneNumber parsedMessage = null;
          try {
            parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            parsedMessage = (org.fancy.mq.core.serializer.protobuf.SimpleMessage.ProtoMessage.PhoneNumber) e.getUnfinishedMessage();
            throw e.unwrapIOException();
          } finally {
            if (parsedMessage != null) {
              mergeFrom(parsedMessage);
            }
          }
          return this;
        }

        private java.lang.Object number_ = "";
        /**
         * <code>string number = 1;</code>
         * @return The number.
         */
        public java.lang.String getNumber() {
          java.lang.Object ref = number_;
          if (!(ref instanceof java.lang.String)) {
            com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            number_ = s;
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <code>string number = 1;</code>
         * @return The bytes for number.
         */
        public com.google.protobuf.ByteString
            getNumberBytes() {
          java.lang.Object ref = number_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            number_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>string number = 1;</code>
         * @param value The number to set.
         * @return This builder for chaining.
         */
        public Builder setNumber(
            java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  
          number_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>string number = 1;</code>
         * @return This builder for chaining.
         */
        public Builder clearNumber() {
          
          number_ = getDefaultInstance().getNumber();
          onChanged();
          return this;
        }
        /**
         * <code>string number = 1;</code>
         * @param value The bytes for number to set.
         * @return This builder for chaining.
         */
        public Builder setNumberBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
          
          number_ = value;
          onChanged();
          return this;
        }

        private int type_ = 0;
        /**
         * <code>.mq.ProtoMessage.PhoneType type = 2;</code>
         * @return The enum numeric value on the wire for type.
         */
        @java.lang.Override public int getTypeValue() {
          return type_;
        }
        /**
         * <code>.mq.ProtoMessage.PhoneType type = 2;</code>
         * @param value The enum numeric value on the wire for type to set.
         * @return This builder for chaining.
         */
        public Builder setTypeValue(int value) {
          
          type_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>.mq.ProtoMessage.PhoneType type = 2;</code>
         * @return The type.
         */
        @java.lang.Override
        public org.fancy.mq.core.serializer.protobuf.SimpleMessage.ProtoMessage.PhoneType getType() {
          @SuppressWarnings("deprecation")
          org.fancy.mq.core.serializer.protobuf.SimpleMessage.ProtoMessage.PhoneType result = org.fancy.mq.core.serializer.protobuf.SimpleMessage.ProtoMessage.PhoneType.valueOf(type_);
          return result == null ? org.fancy.mq.core.serializer.protobuf.SimpleMessage.ProtoMessage.PhoneType.UNRECOGNIZED : result;
        }
        /**
         * <code>.mq.ProtoMessage.PhoneType type = 2;</code>
         * @param value The type to set.
         * @return This builder for chaining.
         */
        public Builder setType(org.fancy.mq.core.serializer.protobuf.SimpleMessage.ProtoMessage.PhoneType value) {
          if (value == null) {
            throw new NullPointerException();
          }
          
          type_ = value.getNumber();
          onChanged();
          return this;
        }
        /**
         * <code>.mq.ProtoMessage.PhoneType type = 2;</code>
         * @return This builder for chaining.
         */
        public Builder clearType() {
          
          type_ = 0;
          onChanged();
          return this;
        }
        @java.lang.Override
        public final Builder setUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.setUnknownFields(unknownFields);
        }

        @java.lang.Override
        public final Builder mergeUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.mergeUnknownFields(unknownFields);
        }


        // @@protoc_insertion_point(builder_scope:mq.ProtoMessage.PhoneNumber)
      }

      // @@protoc_insertion_point(class_scope:mq.ProtoMessage.PhoneNumber)
      private static final org.fancy.mq.core.serializer.protobuf.SimpleMessage.ProtoMessage.PhoneNumber DEFAULT_INSTANCE;
      static {
        DEFAULT_INSTANCE = new org.fancy.mq.core.serializer.protobuf.SimpleMessage.ProtoMessage.PhoneNumber();
      }

      public static org.fancy.mq.core.serializer.protobuf.SimpleMessage.ProtoMessage.PhoneNumber getDefaultInstance() {
        return DEFAULT_INSTANCE;
      }

      private static final com.google.protobuf.Parser<PhoneNumber>
          PARSER = new com.google.protobuf.AbstractParser<PhoneNumber>() {
        @java.lang.Override
        public PhoneNumber parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return new PhoneNumber(input, extensionRegistry);
        }
      };

      public static com.google.protobuf.Parser<PhoneNumber> parser() {
        return PARSER;
      }

      @java.lang.Override
      public com.google.protobuf.Parser<PhoneNumber> getParserForType() {
        return PARSER;
      }

      @java.lang.Override
      public org.fancy.mq.core.serializer.protobuf.SimpleMessage.ProtoMessage.PhoneNumber getDefaultInstanceForType() {
        return DEFAULT_INSTANCE;
      }

    }

    public static final int CODE_FIELD_NUMBER = 1;
    private int code_;
    /**
     * <code>int32 code = 1;</code>
     * @return The code.
     */
    @java.lang.Override
    public int getCode() {
      return code_;
    }

    public static final int NAME_FIELD_NUMBER = 2;
    private volatile java.lang.Object name_;
    /**
     * <code>string name = 2;</code>
     * @return The name.
     */
    @java.lang.Override
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      }
    }
    /**
     * <code>string name = 2;</code>
     * @return The bytes for name.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TIMESTAMP_FIELD_NUMBER = 3;
    private long timestamp_;
    /**
     * <code>int64 timestamp = 3;</code>
     * @return The timestamp.
     */
    @java.lang.Override
    public long getTimestamp() {
      return timestamp_;
    }

    public static final int PHONES_FIELD_NUMBER = 4;
    private java.util.List<org.fancy.mq.core.serializer.protobuf.SimpleMessage.ProtoMessage.PhoneNumber> phones_;
    /**
     * <code>repeated .mq.ProtoMessage.PhoneNumber phones = 4;</code>
     */
    @java.lang.Override
    public java.util.List<org.fancy.mq.core.serializer.protobuf.SimpleMessage.ProtoMessage.PhoneNumber> getPhonesList() {
      return phones_;
    }
    /**
     * <code>repeated .mq.ProtoMessage.PhoneNumber phones = 4;</code>
     */
    @java.lang.Override
    public java.util.List<? extends org.fancy.mq.core.serializer.protobuf.SimpleMessage.ProtoMessage.PhoneNumberOrBuilder> 
        getPhonesOrBuilderList() {
      return phones_;
    }
    /**
     * <code>repeated .mq.ProtoMessage.PhoneNumber phones = 4;</code>
     */
    @java.lang.Override
    public int getPhonesCount() {
      return phones_.size();
    }
    /**
     * <code>repeated .mq.ProtoMessage.PhoneNumber phones = 4;</code>
     */
    @java.lang.Override
    public org.fancy.mq.core.serializer.protobuf.SimpleMessage.ProtoMessage.PhoneNumber getPhones(int index) {
      return phones_.get(index);
    }
    /**
     * <code>repeated .mq.ProtoMessage.PhoneNumber phones = 4;</code>
     */
    @java.lang.Override
    public org.fancy.mq.core.serializer.protobuf.SimpleMessage.ProtoMessage.PhoneNumberOrBuilder getPhonesOrBuilder(
        int index) {
      return phones_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (code_ != 0) {
        output.writeInt32(1, code_);
      }
      if (!getNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, name_);
      }
      if (timestamp_ != 0L) {
        output.writeInt64(3, timestamp_);
      }
      for (int i = 0; i < phones_.size(); i++) {
        output.writeMessage(4, phones_.get(i));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (code_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, code_);
      }
      if (!getNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, name_);
      }
      if (timestamp_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(3, timestamp_);
      }
      for (int i = 0; i < phones_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, phones_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof org.fancy.mq.core.serializer.protobuf.SimpleMessage.ProtoMessage)) {
        return super.equals(obj);
      }
      org.fancy.mq.core.serializer.protobuf.SimpleMessage.ProtoMessage other = (org.fancy.mq.core.serializer.protobuf.SimpleMessage.ProtoMessage) obj;

      if (getCode()
          != other.getCode()) return false;
      if (!getName()
          .equals(other.getName())) return false;
      if (getTimestamp()
          != other.getTimestamp()) return false;
      if (!getPhonesList()
          .equals(other.getPhonesList())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + CODE_FIELD_NUMBER;
      hash = (53 * hash) + getCode();
      hash = (37 * hash) + NAME_FIELD_NUMBER;
      hash = (53 * hash) + getName().hashCode();
      hash = (37 * hash) + TIMESTAMP_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getTimestamp());
      if (getPhonesCount() > 0) {
        hash = (37 * hash) + PHONES_FIELD_NUMBER;
        hash = (53 * hash) + getPhonesList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static org.fancy.mq.core.serializer.protobuf.SimpleMessage.ProtoMessage parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.fancy.mq.core.serializer.protobuf.SimpleMessage.ProtoMessage parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.fancy.mq.core.serializer.protobuf.SimpleMessage.ProtoMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.fancy.mq.core.serializer.protobuf.SimpleMessage.ProtoMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.fancy.mq.core.serializer.protobuf.SimpleMessage.ProtoMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.fancy.mq.core.serializer.protobuf.SimpleMessage.ProtoMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.fancy.mq.core.serializer.protobuf.SimpleMessage.ProtoMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.fancy.mq.core.serializer.protobuf.SimpleMessage.ProtoMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.fancy.mq.core.serializer.protobuf.SimpleMessage.ProtoMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static org.fancy.mq.core.serializer.protobuf.SimpleMessage.ProtoMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.fancy.mq.core.serializer.protobuf.SimpleMessage.ProtoMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.fancy.mq.core.serializer.protobuf.SimpleMessage.ProtoMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(org.fancy.mq.core.serializer.protobuf.SimpleMessage.ProtoMessage prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code mq.ProtoMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:mq.ProtoMessage)
        org.fancy.mq.core.serializer.protobuf.SimpleMessage.ProtoMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.fancy.mq.core.serializer.protobuf.SimpleMessage.internal_static_mq_ProtoMessage_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.fancy.mq.core.serializer.protobuf.SimpleMessage.internal_static_mq_ProtoMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.fancy.mq.core.serializer.protobuf.SimpleMessage.ProtoMessage.class, org.fancy.mq.core.serializer.protobuf.SimpleMessage.ProtoMessage.Builder.class);
      }

      // Construct using org.fancy.mq.core.serializer.protobuf.SimpleMessage.ProtoMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getPhonesFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        code_ = 0;

        name_ = "";

        timestamp_ = 0L;

        if (phonesBuilder_ == null) {
          phones_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          phonesBuilder_.clear();
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.fancy.mq.core.serializer.protobuf.SimpleMessage.internal_static_mq_ProtoMessage_descriptor;
      }

      @java.lang.Override
      public org.fancy.mq.core.serializer.protobuf.SimpleMessage.ProtoMessage getDefaultInstanceForType() {
        return org.fancy.mq.core.serializer.protobuf.SimpleMessage.ProtoMessage.getDefaultInstance();
      }

      @java.lang.Override
      public org.fancy.mq.core.serializer.protobuf.SimpleMessage.ProtoMessage build() {
        org.fancy.mq.core.serializer.protobuf.SimpleMessage.ProtoMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public org.fancy.mq.core.serializer.protobuf.SimpleMessage.ProtoMessage buildPartial() {
        org.fancy.mq.core.serializer.protobuf.SimpleMessage.ProtoMessage result = new org.fancy.mq.core.serializer.protobuf.SimpleMessage.ProtoMessage(this);
        int from_bitField0_ = bitField0_;
        result.code_ = code_;
        result.name_ = name_;
        result.timestamp_ = timestamp_;
        if (phonesBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0)) {
            phones_ = java.util.Collections.unmodifiableList(phones_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.phones_ = phones_;
        } else {
          result.phones_ = phonesBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.fancy.mq.core.serializer.protobuf.SimpleMessage.ProtoMessage) {
          return mergeFrom((org.fancy.mq.core.serializer.protobuf.SimpleMessage.ProtoMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.fancy.mq.core.serializer.protobuf.SimpleMessage.ProtoMessage other) {
        if (other == org.fancy.mq.core.serializer.protobuf.SimpleMessage.ProtoMessage.getDefaultInstance()) return this;
        if (other.getCode() != 0) {
          setCode(other.getCode());
        }
        if (!other.getName().isEmpty()) {
          name_ = other.name_;
          onChanged();
        }
        if (other.getTimestamp() != 0L) {
          setTimestamp(other.getTimestamp());
        }
        if (phonesBuilder_ == null) {
          if (!other.phones_.isEmpty()) {
            if (phones_.isEmpty()) {
              phones_ = other.phones_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensurePhonesIsMutable();
              phones_.addAll(other.phones_);
            }
            onChanged();
          }
        } else {
          if (!other.phones_.isEmpty()) {
            if (phonesBuilder_.isEmpty()) {
              phonesBuilder_.dispose();
              phonesBuilder_ = null;
              phones_ = other.phones_;
              bitField0_ = (bitField0_ & ~0x00000001);
              phonesBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getPhonesFieldBuilder() : null;
            } else {
              phonesBuilder_.addAllMessages(other.phones_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.fancy.mq.core.serializer.protobuf.SimpleMessage.ProtoMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.fancy.mq.core.serializer.protobuf.SimpleMessage.ProtoMessage) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int code_ ;
      /**
       * <code>int32 code = 1;</code>
       * @return The code.
       */
      @java.lang.Override
      public int getCode() {
        return code_;
      }
      /**
       * <code>int32 code = 1;</code>
       * @param value The code to set.
       * @return This builder for chaining.
       */
      public Builder setCode(int value) {
        
        code_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 code = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearCode() {
        
        code_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object name_ = "";
      /**
       * <code>string name = 2;</code>
       * @return The name.
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string name = 2;</code>
       * @return The bytes for name.
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string name = 2;</code>
       * @param value The name to set.
       * @return This builder for chaining.
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string name = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearName() {
        
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>string name = 2;</code>
       * @param value The bytes for name to set.
       * @return This builder for chaining.
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        name_ = value;
        onChanged();
        return this;
      }

      private long timestamp_ ;
      /**
       * <code>int64 timestamp = 3;</code>
       * @return The timestamp.
       */
      @java.lang.Override
      public long getTimestamp() {
        return timestamp_;
      }
      /**
       * <code>int64 timestamp = 3;</code>
       * @param value The timestamp to set.
       * @return This builder for chaining.
       */
      public Builder setTimestamp(long value) {
        
        timestamp_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 timestamp = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearTimestamp() {
        
        timestamp_ = 0L;
        onChanged();
        return this;
      }

      private java.util.List<org.fancy.mq.core.serializer.protobuf.SimpleMessage.ProtoMessage.PhoneNumber> phones_ =
        java.util.Collections.emptyList();
      private void ensurePhonesIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          phones_ = new java.util.ArrayList<org.fancy.mq.core.serializer.protobuf.SimpleMessage.ProtoMessage.PhoneNumber>(phones_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          org.fancy.mq.core.serializer.protobuf.SimpleMessage.ProtoMessage.PhoneNumber, org.fancy.mq.core.serializer.protobuf.SimpleMessage.ProtoMessage.PhoneNumber.Builder, org.fancy.mq.core.serializer.protobuf.SimpleMessage.ProtoMessage.PhoneNumberOrBuilder> phonesBuilder_;

      /**
       * <code>repeated .mq.ProtoMessage.PhoneNumber phones = 4;</code>
       */
      public java.util.List<org.fancy.mq.core.serializer.protobuf.SimpleMessage.ProtoMessage.PhoneNumber> getPhonesList() {
        if (phonesBuilder_ == null) {
          return java.util.Collections.unmodifiableList(phones_);
        } else {
          return phonesBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .mq.ProtoMessage.PhoneNumber phones = 4;</code>
       */
      public int getPhonesCount() {
        if (phonesBuilder_ == null) {
          return phones_.size();
        } else {
          return phonesBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .mq.ProtoMessage.PhoneNumber phones = 4;</code>
       */
      public org.fancy.mq.core.serializer.protobuf.SimpleMessage.ProtoMessage.PhoneNumber getPhones(int index) {
        if (phonesBuilder_ == null) {
          return phones_.get(index);
        } else {
          return phonesBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .mq.ProtoMessage.PhoneNumber phones = 4;</code>
       */
      public Builder setPhones(
          int index, org.fancy.mq.core.serializer.protobuf.SimpleMessage.ProtoMessage.PhoneNumber value) {
        if (phonesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePhonesIsMutable();
          phones_.set(index, value);
          onChanged();
        } else {
          phonesBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .mq.ProtoMessage.PhoneNumber phones = 4;</code>
       */
      public Builder setPhones(
          int index, org.fancy.mq.core.serializer.protobuf.SimpleMessage.ProtoMessage.PhoneNumber.Builder builderForValue) {
        if (phonesBuilder_ == null) {
          ensurePhonesIsMutable();
          phones_.set(index, builderForValue.build());
          onChanged();
        } else {
          phonesBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .mq.ProtoMessage.PhoneNumber phones = 4;</code>
       */
      public Builder addPhones(org.fancy.mq.core.serializer.protobuf.SimpleMessage.ProtoMessage.PhoneNumber value) {
        if (phonesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePhonesIsMutable();
          phones_.add(value);
          onChanged();
        } else {
          phonesBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .mq.ProtoMessage.PhoneNumber phones = 4;</code>
       */
      public Builder addPhones(
          int index, org.fancy.mq.core.serializer.protobuf.SimpleMessage.ProtoMessage.PhoneNumber value) {
        if (phonesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePhonesIsMutable();
          phones_.add(index, value);
          onChanged();
        } else {
          phonesBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .mq.ProtoMessage.PhoneNumber phones = 4;</code>
       */
      public Builder addPhones(
          org.fancy.mq.core.serializer.protobuf.SimpleMessage.ProtoMessage.PhoneNumber.Builder builderForValue) {
        if (phonesBuilder_ == null) {
          ensurePhonesIsMutable();
          phones_.add(builderForValue.build());
          onChanged();
        } else {
          phonesBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .mq.ProtoMessage.PhoneNumber phones = 4;</code>
       */
      public Builder addPhones(
          int index, org.fancy.mq.core.serializer.protobuf.SimpleMessage.ProtoMessage.PhoneNumber.Builder builderForValue) {
        if (phonesBuilder_ == null) {
          ensurePhonesIsMutable();
          phones_.add(index, builderForValue.build());
          onChanged();
        } else {
          phonesBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .mq.ProtoMessage.PhoneNumber phones = 4;</code>
       */
      public Builder addAllPhones(
          java.lang.Iterable<? extends org.fancy.mq.core.serializer.protobuf.SimpleMessage.ProtoMessage.PhoneNumber> values) {
        if (phonesBuilder_ == null) {
          ensurePhonesIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, phones_);
          onChanged();
        } else {
          phonesBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .mq.ProtoMessage.PhoneNumber phones = 4;</code>
       */
      public Builder clearPhones() {
        if (phonesBuilder_ == null) {
          phones_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          phonesBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .mq.ProtoMessage.PhoneNumber phones = 4;</code>
       */
      public Builder removePhones(int index) {
        if (phonesBuilder_ == null) {
          ensurePhonesIsMutable();
          phones_.remove(index);
          onChanged();
        } else {
          phonesBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .mq.ProtoMessage.PhoneNumber phones = 4;</code>
       */
      public org.fancy.mq.core.serializer.protobuf.SimpleMessage.ProtoMessage.PhoneNumber.Builder getPhonesBuilder(
          int index) {
        return getPhonesFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .mq.ProtoMessage.PhoneNumber phones = 4;</code>
       */
      public org.fancy.mq.core.serializer.protobuf.SimpleMessage.ProtoMessage.PhoneNumberOrBuilder getPhonesOrBuilder(
          int index) {
        if (phonesBuilder_ == null) {
          return phones_.get(index);  } else {
          return phonesBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .mq.ProtoMessage.PhoneNumber phones = 4;</code>
       */
      public java.util.List<? extends org.fancy.mq.core.serializer.protobuf.SimpleMessage.ProtoMessage.PhoneNumberOrBuilder> 
           getPhonesOrBuilderList() {
        if (phonesBuilder_ != null) {
          return phonesBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(phones_);
        }
      }
      /**
       * <code>repeated .mq.ProtoMessage.PhoneNumber phones = 4;</code>
       */
      public org.fancy.mq.core.serializer.protobuf.SimpleMessage.ProtoMessage.PhoneNumber.Builder addPhonesBuilder() {
        return getPhonesFieldBuilder().addBuilder(
            org.fancy.mq.core.serializer.protobuf.SimpleMessage.ProtoMessage.PhoneNumber.getDefaultInstance());
      }
      /**
       * <code>repeated .mq.ProtoMessage.PhoneNumber phones = 4;</code>
       */
      public org.fancy.mq.core.serializer.protobuf.SimpleMessage.ProtoMessage.PhoneNumber.Builder addPhonesBuilder(
          int index) {
        return getPhonesFieldBuilder().addBuilder(
            index, org.fancy.mq.core.serializer.protobuf.SimpleMessage.ProtoMessage.PhoneNumber.getDefaultInstance());
      }
      /**
       * <code>repeated .mq.ProtoMessage.PhoneNumber phones = 4;</code>
       */
      public java.util.List<org.fancy.mq.core.serializer.protobuf.SimpleMessage.ProtoMessage.PhoneNumber.Builder> 
           getPhonesBuilderList() {
        return getPhonesFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          org.fancy.mq.core.serializer.protobuf.SimpleMessage.ProtoMessage.PhoneNumber, org.fancy.mq.core.serializer.protobuf.SimpleMessage.ProtoMessage.PhoneNumber.Builder, org.fancy.mq.core.serializer.protobuf.SimpleMessage.ProtoMessage.PhoneNumberOrBuilder> 
          getPhonesFieldBuilder() {
        if (phonesBuilder_ == null) {
          phonesBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              org.fancy.mq.core.serializer.protobuf.SimpleMessage.ProtoMessage.PhoneNumber, org.fancy.mq.core.serializer.protobuf.SimpleMessage.ProtoMessage.PhoneNumber.Builder, org.fancy.mq.core.serializer.protobuf.SimpleMessage.ProtoMessage.PhoneNumberOrBuilder>(
                  phones_,
                  ((bitField0_ & 0x00000001) != 0),
                  getParentForChildren(),
                  isClean());
          phones_ = null;
        }
        return phonesBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:mq.ProtoMessage)
    }

    // @@protoc_insertion_point(class_scope:mq.ProtoMessage)
    private static final org.fancy.mq.core.serializer.protobuf.SimpleMessage.ProtoMessage DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new org.fancy.mq.core.serializer.protobuf.SimpleMessage.ProtoMessage();
    }

    public static org.fancy.mq.core.serializer.protobuf.SimpleMessage.ProtoMessage getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ProtoMessage>
        PARSER = new com.google.protobuf.AbstractParser<ProtoMessage>() {
      @java.lang.Override
      public ProtoMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ProtoMessage(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ProtoMessage> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ProtoMessage> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public org.fancy.mq.core.serializer.protobuf.SimpleMessage.ProtoMessage getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_mq_ProtoMessage_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_mq_ProtoMessage_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_mq_ProtoMessage_PhoneNumber_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_mq_ProtoMessage_PhoneNumber_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rmessage.proto\022\002mq\"\341\001\n\014ProtoMessage\022\014\n\004" +
      "code\030\001 \001(\005\022\014\n\004name\030\002 \001(\t\022\021\n\ttimestamp\030\003 " +
      "\001(\003\022,\n\006phones\030\004 \003(\0132\034.mq.ProtoMessage.Ph" +
      "oneNumber\032G\n\013PhoneNumber\022\016\n\006number\030\001 \001(\t" +
      "\022(\n\004type\030\002 \001(\0162\032.mq.ProtoMessage.PhoneTy" +
      "pe\"+\n\tPhoneType\022\010\n\004HOME\020\000\022\n\n\006MOBILE\020\001\022\010\n" +
      "\004WORK\020\002B6\n%org.fancy.mq.core.serializer." +
      "protobufB\rSimpleMessageb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_mq_ProtoMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_mq_ProtoMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_mq_ProtoMessage_descriptor,
        new java.lang.String[] { "Code", "Name", "Timestamp", "Phones", });
    internal_static_mq_ProtoMessage_PhoneNumber_descriptor =
      internal_static_mq_ProtoMessage_descriptor.getNestedTypes().get(0);
    internal_static_mq_ProtoMessage_PhoneNumber_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_mq_ProtoMessage_PhoneNumber_descriptor,
        new java.lang.String[] { "Number", "Type", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
